" Turn the syntax highlight on
syntax on

" Set tabstop and shit
set tabstop=4
set shiftwidth=4
set softtabstop=4

" Set indent settings
set autoindent
set smartindent

" Set colorscheme
colorscheme habamax

" Turn off the auto-add comment signature
set formatoptions-=ro

" Set color
set termguicolors

" set the mouse
set mouse=a 

" Turn the line number on
set number

" Disable compatibility with vi
set nocompatible 

" Enable filetype detection 
filetype on 
filetype plugin on 
filetype indent on 

" Search down into subfolder
" Provides tabs-completion for all file related-tasks
set path+=**

" Display all matching files when tab complete
set wildmenu 

" Display status bar
set laststatus=2

" Automatically wrap text that extends beyond the screen
set wrap

" Set encoding to a particular type
set encoding=utf-8

